version: '3.8'

services:
  web:
    build: .
    container_name: django_asgi
    command: daphne -b 0.0.0.0 -p 8000 mini_proj.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mini_proj.settings
      - DEBUG=False

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mini_proj.settings
