# Generated by Django 5.1.6 on 2025-02-27 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('total_volume', models.PositiveIntegerField(default=0)),
                ('avg_trade_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
