# Generated by Django 5.1.6 on 2025-02-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
